env:
  global:
    - DOCKER_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - DOCKER_BRANCH=${DOCKER_BRANCH//[\@\/]/-}
    - TESTS_TYPE=${TESTS_TYPE}
    - TEST_TAG=${TEST_TAG}
    - BRANCH_WITH_FULL_TESTS=master
language: node_js
node_js:
  - '10'
services:
  - docker
before_install:
  - npm install -g npm@latest
install:
  - npm install
  - npm run prod
jobs:
  include:
    - stage: 'Docker build'
      script:
        - docker pull "securetrading1/js-payments-card"
        - docker build . --tag "securetrading1/js-payments-card:$DOCKER_BRANCH"
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker push "securetrading1/js-payments-card"
        - cd js-payments-testing
        - git pull --ff-only origin master
        - docker build . --build-arg "CODE_REPO=js-payments-card" --build-arg "CODE_VERSION=$DOCKER_BRANCH" --tag "securetrading1/js-payments-testing:$DOCKER_BRANCH"
        - docker push "securetrading1/js-payments-testing"
    - stage: 'Test'
      name: 'Unit tests'
      script:
        - npm run coverage
        - npm run snyk
    - name: 'Behavioural test: chrome 76, Windows 10'
      if: env(TESTS_TYPE)=fullTest OR env(TESTS_TYPE)=smokeTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos=Windows -Dos_version=10 -Dbrowser=chrome -Dbrowser_version=76.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: chrome 75, Windows 8.1'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos=Windows -Dos_version=8.1 -Dbrowser=chrome -Dbrowser_version=75.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: chrome 76, Windows 8'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos=Windows -Dos_version=8 -Dbrowser=chrome -Dbrowser_version=76.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: chrome 76, OS X Mojave'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos="OS X" -Dos_version=Mojave -Dbrowser=chrome -Dbrowser_version=76.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: chrome 75, OS X High Sierra'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos="OS X" -Dos_version="High Sierra" -Dbrowser=chrome -Dbrowser_version=75.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: chrome 76, OS X Sierra'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos="OS X" -Dos_version=Sierra -Dbrowser=chrome -Dbrowser_version=76.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: firefox 68, Windows 10'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos=Windows -Dos_version=10 -Dbrowser=Firefox -Dbrowser_version=68.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: firefox 67, Windows 8.1'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos=Windows -Dos_version=8.1 -Dbrowser=Firefox -Dbrowser_version=67.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: firefox 68, OS X Mojave'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos="OS X" -Dos_version=Mojave -Dbrowser=Firefox -Dbrowser_version=68.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: firefox 67, OS X High Sierra'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos="OS X" -Dos_version="High Sierra" -Dbrowser=Firefox -Dbrowser_version=67.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: firefox 68, OS X Sierra'
      if: branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos="OS X" -Dos_version=Sierra -Dbrowser=Firefox -Dbrowser_version=68.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: ie 11, Windows 10'
      if: env(TESTS_TYPE)=fullTest OR env(TESTS_TYPE)=smokeTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos=Windows -Dos_version=10 -Dbrowser=IE -Dbrowser_version=11.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: edge 18, Windows 10'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos=Windows -Dos_version=10 -Dbrowser=Edge -Dbrowser_version=18.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: edge 17, Windows 10'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos=Windows -Dos_version=10 -Dbrowser=Edge -Dbrowser_version=17.0 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: safari 12.1, OS X Mojave'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos="OS X" -Dos_version=Mojave -Dbrowser=Safari -Dbrowser_version=12.1 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: safari 11.1, OS X High Sierra'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Dos="OS X" -Dos_version="High Sierra" -Dbrowser=Safari -Dbrowser_version=11.1 -Dresolution=1920x1080 -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Samsung Galaxy Note 9, Android 8.1'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Samsung Galaxy Note 9" -Dos_version=8.1 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Samsung Galaxy S9, Android 8.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Samsung Galaxy S9" -Dos_version=8.0 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Samsung Galaxy S9 Plus, Android 9.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Samsung Galaxy S9 Plus" -Dos_version=9.0 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Samsung Galaxy S8, Android 7.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Samsung Galaxy S8" -Dos_version=7.0 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Samsung Galaxy S7, Android 6.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Samsung Galaxy S7" -Dos_version=6.0 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Samsung Galaxy Tab S3, Android 7.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Samsung Galaxy Tab S3" -Dos_version=7.0 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Google Pixel 3, Android 9.0'
      if: env(TESTS_TYPE)=fullTestv
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Google Pixel 3" -Dos_version=9.0 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Google Pixel, Android 8.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Google Pixel" -Dos_version=8.0 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Google Nexus 6, Android 6.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Google Nexus 6" -Dos_version=6.0 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Google Nexus 9, Android 5.1'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Google Nexus 9" -Dos_version=5.1 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: Google Nexus 5, Android 4.4'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="Google Nexus 5" -Dos_version=4.4 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: iPhone XS, iOS 12.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="iPhone XS" -Dos_version=12 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: iPhone XS Max, iOS 12.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="iPhone XS Max" -Dos_version=12 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: iPhone XR, iOS 12.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="iPhone XR" -Dos_version=12 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: iPhone X, iOS 11.0'
      if: env(TESTS_TYPE)=fullTest OR env(TESTS_TYPE)=smokeTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="iPhone X" -Dos_version=11 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: iPhone 8, iOS 11.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="iPhone 8" -Dos_version=11 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: iPhone SE, iOS 11.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="iPhone SE" -Dos_version=11 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
    - name: 'Behavioural test: iPad Mini 4, iOS 11.0'
      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - npm run behave -- mvn install -DLOCAL=true -Ddevice="iPad Mini 4" -Dos_version=11 -Dreal_mobile=true -Dcucumber.options="--tags $TEST_TAG"
after_success:
  - cat ./coverage/lcov.info | coveralls
addons:
  browserstack:
    forcelocal: true
    username:
      secure: UbH2KGZ8EO8namxiBRQldk1ANcRHQkxQbF+xWlz360K2+2vFym6H/ujy3N2eZxyMlgSZes1Rgt0kmsQrFTCVPU5/5jZIgzvLc2kHU3CKulxqMkBXPhqz/V4bVTFDoC6rScIooZt2+Gb9JqryitDOa8DbQbrypq5y3Szdh00Lqahjy8WuVigu8gBfIFOJqG9egUu2Dk9eV9PtfU9PTZ+V4GdHwDXWA9PJoAo2Epbh/pVXrwNGdx68rOObNbPew3/4ckKHfghKyUcwpUEg+TaILkXcsKvkJ2KXaInVFe3Efo/f51i3x5w2uSlR98gqmwMmn+jkxrr2EE5hXvHLgHEj3usPvJPk0LpAHYmjmch69qqadER5pRM/ztOHyf5Uq9DM8ZTMN3X1HLt3o5AKywZ6JGXiMBUD/d6xZkBXGbEz8arMgCHtxP9/FIw/AlcIf8yUteghuXV1jqbC/4H7XLSX+h4iZ8B/InVncKEjGeH+lFLmx4IYNH9k3dwzh42YGwx+XMNJFbALD7NzS5v8uZdaFUb+Yh4PX8+dqYUmL0idIhG60XOKaRYVOPqc2lSTAIqD/Oz3RMpew3ZXs/+jM1C0b0lztnS399Oc4q8NmBJ9J6GKtJtiff7GbRCKqCByV+wl+jF3i8TxmuirZ8f3tO95wkhd+WVtV06KsTIkfPaOAL0=
    access_key:
      secure: CMmqBS7cJSX0hh7BdifquuxSU4WenqojHYi/juZdMHhcuG02k9FmdoHVLo+C1ypeTcOaUS2NPCcE7A3TNHgMmz1UF2q4jfGYXTweNPQorRHfxTllSz8ighzWAH26kkMD+S7WE42LzWaUwsOW06qiahaYAQxv93xDrnBHTTG1YuEM80thSjRS70K9t14TmWR+7AnUVKlE+BKda+vCn52Rjo0+mLXEXHOAEnQNCL2kP+DwHKzE32ZqtGdTITgGuiN3fZOy6A2ZMZbDs0+7VJFHxuOSMsM4JlgowcQqWIQMsyLU2O8J1HyUUfZIfGSnRmJRhAn+oF+jZnZ5dXMnGCZHXqQDYqEIXM5gAE2nU61E24iAwvu3JpqkRtoZk4c47mf1WerfpLBzOq/BYGBFdP154I8hVgZfn2mkZ8l/f29Mj8VZ+TALoTGd63HvKT72haUIJBQSXoPIrBcQ4ws8WMOkKRa5mhpjTN/Vf+LE1YoE81lI3APF7fqBV2o5+o8AgcD4dXW1HWbPMFpEQtnM1JddjAjO8xkEzL3clAfka1VqWJRn5XI1N8WipB3T+xQI9aKS85upvzpMFQtJe+3jipKHmu+P918A1dKeqhVNHkYTFXKDXonKq//i4mIYm7sgfTQOQZ5pkgee8ZlQ5jUmMR7Gsn0gDJ20tJfsC/BvKcPIpW4=
  hosts:
    - webservices.securetrading.net
    - merchant.example.com
    - thirdparty.example.com
