env:
  global:
    - DOCKER_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - DOCKER_BRANCH=${DOCKER_BRANCH//[\@\/]/-}
    - TESTS_TYPE=${TESTS_TYPE}
    - TEST_TAG=${TEST_TAG}
    - BRANCH_WITH_FULL_TESTS=master
    - APP_REPO=js-payments
    - APP_BRANCH=$DOCKER_BRANCH
    - DOCKER_TAG="docker-compose -f py-payments-testing/docker-compose.yml run"
    - RUN_TESTS="-e REMOTE=true tests poetry run behave features"
language: node_js
node_js:
  - 10
services:
  - docker
install: skip
before_script:
  - git clone --branch=feature/sample-test --single-branch --depth=1 https://github.com/SecureTrading/py-payments-testing.git
  - docker-compose -f py-payments-testing/docker-compose.yml pull
  - docker-compose -f py-payments-testing/docker-compose.yml up -d
jobs:
  include:
    - stage: Unit tests & Docker build
      name: Unit tests
      before_script: skip
      script:
        - npm install
        - npm run coverage
        - npm run snyk
    - name: Build docker
      before_script: skip
      script:
        - docker build . --tag "securetrading1/js-payments-card:$DOCKER_BRANCH"
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker push "securetrading1/js-payments-card:$DOCKER_BRANCH"
    - stage: Behavioral test
      name: 'Chrome latest, Docker'
      if: env(TESTS_TYPE)=fullTest OR env(TESTS_TYPE)=smokeTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - ${DOCKER_TAG} tests poetry run behave features --tags=$TEST_TAG
    - name: "Behavioural test: chrome 76, Windows 10"
      if: env(TESTS_TYPE)=fullTest OR env(TESTS_TYPE)=smokeTest OR branch = env(BRANCH_WITH_FULL_TESTS)
      script:
        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=chrome -e BROWSER_VERSION=76.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: chrome 75, Windows 8.1"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=8.1 -e BROWSER=chrome -e BROWSER_VERSION=75.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: chrome 76, Windows 8"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=8 -e BROWSER=chrome -e BROWSER_VERSION=76.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: chrome 76, OS X Mojave"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION=Mojave -e BROWSER=chrome -e BROWSER_VERSION=76.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: chrome 75, OS X High Sierra"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION="High Sierra" -e BROWSER=chrome -e BROWSER_VERSION=75.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: chrome 76, OS X Sierra"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION=Sierra -e BROWSER=chrome -e BROWSER_VERSION=76.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: firefox 68, Windows 10"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=Firefox -e BROWSER_VERSION=68.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: firefox 67, Windows 8.1"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=8.1 -e BROWSER=Firefox -e BROWSER_VERSION=67.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: firefox 68, Windows 7"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=7 -e BROWSER=Firefox -e BROWSER_VERSION=68.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: firefox 68, OS X Mojave"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION=Mojave -e BROWSER=Firefox -e BROWSER_VERSION=68.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: firefox 67, OS X High Sierra"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION="High Sierra" -e BROWSER=Firefox -e BROWSER_VERSION=67.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: firefox 68, OS X Sierra"
#      if: branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - npm run behave - mvn install -e OS="OS X" -e OS_VERSION=Sierra -e BROWSER=Firefox -e BROWSER_VERSION=68.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: ie 11, Windows 10"
#      if: env(TESTS_TYPE)=fullTest OR env(TESTS_TYPE)=smokeTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=IE -e BROWSER_VERSION=11.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: ie 10, Windows 8"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=8 -e BROWSER=IE -e BROWSER_VERSION=10.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: edge 18, Windows 10"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=Edge -e BROWSER_VERSION=18.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: edge 17, Windows 10"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=Edge -e BROWSER_VERSION=17.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: safari 12.1, OS X Mojave"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION=Mojave -e BROWSER=Safari -e BROWSER_VERSION=12.1 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: safari 11.1, OS X High Sierra"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION="High Sierra" -e BROWSER=Safari -e BROWSER_VERSION=11.1 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: safari 10.1, OS X Sierra"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION=Sierra -e BROWSER=Safari -e BROWSER_VERSION=10.1 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Samsung Galaxy Note 9, Android 8.1"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy Note 9" -e OS_VERSION=8.1 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Samsung Galaxy S9, Android 8.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy S9" -e OS_VERSION=8.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Samsung Galaxy S9 Plus, Android 9.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy S9 Plus" -e OS_VERSION=9.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Samsung Galaxy S8, Android 7.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy S8" -e OS_VERSION=7.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Samsung Galaxy S7, Android 6.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy S7" -e OS_VERSION=6.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Samsung Galaxy Tab S3, Android 7.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy Tab S3" -e OS_VERSION=7.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Google Pixel 3, Android 9.0"
#      if: env(TESTS_TYPE)=fullTestv
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Google Pixel 3" -e OS_VERSION=9.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Google Pixel, Android 8.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Google Pixel" -e OS_VERSION=8.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Google Pixel, Android 7.1"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Google Pixel" -e OS_VERSION=7.1 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Google Nexus 6, Android 6.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Google Nexus 6" -e OS_VERSION=6.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Google Nexus 9, Android 5.1"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Google Nexus 9" -e OS_VERSION=5.1 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: Google Nexus 5, Android 4.4"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="Google Nexus 5" -e OS_VERSION=4.4 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: iPhone XS, iOS 12.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="iPhone XS" -e OS_VERSION=12 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: iPhone XS Max, iOS 12.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="iPhone XS Max" -e OS_VERSION=12 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: iPhone XR, iOS 12.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="iPhone XR" -e OS_VERSION=12 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: iPhone X, iOS 11.0"
#      if: env(TESTS_TYPE)=fullTest OR env(TESTS_TYPE)=smokeTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="iPhone X" -e OS_VERSION=11 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: iPhone 8, iOS 11.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="iPhone 8" -e OS_VERSION=11 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: iPhone SE, iOS 11.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="iPhone SE" -e OS_VERSION=11 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: iPad Pro 12.9 2018, iOS 12.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="iPad Pro 12.9 2018" -e OS_VERSION=12 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
#    - name: "Behavioural test: iPad Mini 4, iOS 11.0"
#      if: env(TESTS_TYPE)=fullTest OR branch = env(BRANCH_WITH_FULL_TESTS)
#      script:
#        - ${DOCKER_TAG} -e DEVICE="iPad Mini 4" -e OS_VERSION=11 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER ${RUN_TESTS} --tags=$TEST_TAG
after_success:
  - cat ./coverage/lcov.info | coveralls
addons:
  browserstack:
    forcelocal: true
    username:
      secure: gqmH3YaHQw+ggkVIl+FYmKdblYlrjQBbHHsMpNI3afFtms3Kwug2qjT59vQBnnVsHAuSJx7Af+/7xk52oRIUeiylkmZfvgelergOcI+Pzs2/rbLhmdaXcQyXijzCWkF+iVBZL3MXm1QjukoYkVQXSiwVDa3bMf5MXfjXp3UJH/AgR/rlTTDbHFCAemdQY6H6JTgD+qPmZtT72duKQVGX6sZKvRxFNMPpgwYvPYMsjfzmdJmUWE7FzvGJN/357NZYZPLV/Xc7WD1W1LFDzavlFS1j6u+UTlZMBIq2/lbThBeY7WjoGb7eTYMDnV3oaScg7fssJESa3MgU4tXPW9NL7o1w8ihzjv2e4rvK8k1xfbOTDlwKJ+GvVv4YOjmt2T2G2mq7c5GxWdvNIi3r7CCmalv3cHUVKirUZuVu9lpwf4ec4pDnf4iwXIIQOosK0wb0m0OO0uoLdx8vESNUTY+oIQaUyHaR8xJs0KH4TO8pXLYi3pAIEz1GIbejQqctLRuKWwElwqh0hKaDJ/7+38yQUm7UCI1jR1IjPiVtWSMo3QeRtVH+YCX+fI7o1sqpxS/nREn4aa7YhMpfHYY/oFHe3FlSYgTtdp+icvBV/qAxWEh5yyepL2VeoblgbZJA/yWm1G5ISA906ZZuLNyaracYs3+XGQFpnfR082xYE8OZx7M=
    access_key:
      secure: Ve3TJXy4GrvlU1H6wy/3QPDPObiOl6AlH5fyQbiTygfsQq7xFTqFLYHjgn4ikzPF5u9lQ3F83NXm8A3OsxropNB3DdTpNlg4faqjiQkiyR+rom2QUe7n0gYzTKOeM5/qIZL67wSfYKYKIjP+vlbgUwn+BAUOT68rTYZ5+5WnihxcREgs4UrmYDfekMtPrm8uHPp0HItCOnrinMIyqtLNddp9ytMidkREVvepffQ/4Zs/5n7jD17o7Ut6+nKaNY0iFIVv9TwSEbI++2U1BDFgzxm3vzGpt3Zg+mwPK7C3Q9rI4vjquN9v2R4XsLxmkzWciZLFbysodOMoyEO96piekI34aLYA0zJr5eMZYGjfvRnzS0cScZlyuzddGp/KjMocuwd1B0mrN6gl5oploEelSCHIAFc8xJkW8wi6bS1ivSeZ5IAKR3RDpfXxzP8jT8EWlPbumeauOB5U0T4f1Xz9x93LJnFk8HKyja9GIboxZ+lw6cTmrgAHTUssx/S+MbJxzxr5MPG0Ubqlh92HvqSFbiKzC8m/p0ZVnU/HLfDdB7yz+qJ5/PY4G2k5o82qNAvpjWpaKNibW/bMivgXtPU7hTTmihZsa/Q8JTvjOZcnSp6e+9AAKB5FaioFqvSii319NMuuTlyKXOEPk79OwSHNWFg7iPG6BPVwPXwiR3X8x+s=
  hosts:
    - webservices.securetrading.net
    - merchant.example.com
    - thirdparty.example.com
